
var ScifiBot = ScifiBot || {};

ScifiBot.DATA = {
    1: {"Title":"Terminator 1: Judgment Day","Year":"1991","Rated":"R","Released":"03 Jul 1991","Runtime":"137 min","Genre":"Action, Sci-Fi, Thriller","Director":"James Cameron","Writer":"James Cameron, William Wisher Jr.","Actors":"Arnold Schwarzenegger, Linda Hamilton, Edward Furlong, Robert Patrick","Plot":"A cyborg, identical to the one who failed to kill Sarah Connor, must now protect her young son, John Connor, from a more advanced cyborg, made out of liquid metal.","Language":"English, Spanish","Country":"USA, France","Awards":"Won 4 Oscars. Another 21 wins & 22 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BZDM2YjYwYWMtMWZlNi00ZDQxLWExMDctMDAzNzQ0OTkzZjljXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg","Metascore":"75","imdbRating":"8.5","imdbVotes":"759,731","imdbID":"tt0103064","Type":"movie","Response":"True"},
    2: {"Title":"Terminator 2: Judgment Day","Year":"1991","Rated":"R","Released":"03 Jul 1991","Runtime":"137 min","Genre":"Action, Sci-Fi, Thriller","Director":"James Cameron","Writer":"James Cameron, William Wisher Jr.","Actors":"Arnold Schwarzenegger, Linda Hamilton, Edward Furlong, Robert Patrick","Plot":"A cyborg, identical to the one who failed to kill Sarah Connor, must now protect her young son, John Connor, from a more advanced cyborg, made out of liquid metal.","Language":"English, Spanish","Country":"USA, France","Awards":"Won 4 Oscars. Another 21 wins & 22 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BZDM2YjYwYWMtMWZlNi00ZDQxLWExMDctMDAzNzQ0OTkzZjljXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg","Metascore":"75","imdbRating":"8.5","imdbVotes":"759,731","imdbID":"tt0103064","Type":"movie","Response":"True"},
    3: {"Title":"Terminator 3: Judgment Day","Year":"1991","Rated":"R","Released":"03 Jul 1991","Runtime":"137 min","Genre":"Action, Sci-Fi, Thriller","Director":"James Cameron","Writer":"James Cameron, William Wisher Jr.","Actors":"Arnold Schwarzenegger, Linda Hamilton, Edward Furlong, Robert Patrick","Plot":"A cyborg, identical to the one who failed to kill Sarah Connor, must now protect her young son, John Connor, from a more advanced cyborg, made out of liquid metal.","Language":"English, Spanish","Country":"USA, France","Awards":"Won 4 Oscars. Another 21 wins & 22 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BZDM2YjYwYWMtMWZlNi00ZDQxLWExMDctMDAzNzQ0OTkzZjljXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg","Metascore":"75","imdbRating":"8.5","imdbVotes":"759,731","imdbID":"tt0103064","Type":"movie","Response":"True"},
    4: {"Title":"Terminator 4: Judgment Day","Year":"1991","Rated":"R","Released":"03 Jul 1991","Runtime":"137 min","Genre":"Action, Sci-Fi, Thriller","Director":"James Cameron","Writer":"James Cameron, William Wisher Jr.","Actors":"Arnold Schwarzenegger, Linda Hamilton, Edward Furlong, Robert Patrick","Plot":"A cyborg, identical to the one who failed to kill Sarah Connor, must now protect her young son, John Connor, from a more advanced cyborg, made out of liquid metal.","Language":"English, Spanish","Country":"USA, France","Awards":"Won 4 Oscars. Another 21 wins & 22 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BZDM2YjYwYWMtMWZlNi00ZDQxLWExMDctMDAzNzQ0OTkzZjljXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg","Metascore":"75","imdbRating":"8.5","imdbVotes":"759,731","imdbID":"tt0103064","Type":"movie","Response":"True"}
};
