// Automatically generated by Scifibot command line manager.
// Date: 2016-12-31 15:48:52

var ScifiBot = ScifiBot || {};

ScifiBot.config.DATABASE_DATA =
{
    "1": {
        "id": 1,
        "type": 1,
        "name": "Test",
        "publisher": null,
        "year": null,
        "rated": null,
        "released": null,
        "runtime": null,
        "genre": null,
        "director": null,
        "plot": null,
        "teaser": null,
        "imdb_rating": null,
        "metascore": null,
        "rotten_tomatoes": null,
        "trailer": null,
        "modified": 1482777363,
        "created": null
    },
    "2": {
        "id": 2,
        "type": 1,
        "name": "Again",
        "publisher": null,
        "year": null,
        "rated": null,
        "released": null,
        "runtime": null,
        "genre": null,
        "director": null,
        "plot": "Updated right from the server!",
        "teaser": null,
        "imdb_rating": null,
        "metascore": null,
        "rotten_tomatoes": null,
        "trailer": null,
        "modified": 1682777365,
        "created": null
    }
};

