<?php

@include(dirname(__FILE__) . '/config.local.php');
@include(dirname(__FILE__) . '/config.php');

if (php_sapi_name() != 'cli') {
    echo 'This script should be run from the command line.';
    exit();
}

$aShortOptions = 'h::';
$aOptions = array(
    "sql:",
    "dump",
    "help::"
);

$aArgs = getopt($aShortOptions, $aOptions);

if($argc <= 1 || isset($aArgs['help']) || isset($aArgs['h'])) {
	echo "ScifiBot - command line manager. \n";
	echo "(c) Copyright 2016, Fernando Bevilacqua. \n\n";
	echo "Usage: \n";
	echo " php ".basename($_SERVER['PHP_SELF']) . " [options]\n\n";
	echo "Options:\n";
    echo " --sql=<path>     Run the sql commands in the file loaded from <path>.\n\n";
    echo " --dump           Output the database as a js file.\n\n";
	echo " --help, -h       Show this help message..\n";
	echo "\n";
	exit(1);
}

$aDb = new PDO('sqlite:' . DB_FILE);
$aDb->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

$aSql = isset($aArgs['sql']) ? $aArgs['sql'] : '';
$aDump = isset($aArgs['dump']);

if($aSql != '') {
	 if(!file_exists($aSql)) {
		 echo "File informed by --sql does not exist: '" . $aSql . "'\n";
		 exit(2);
	 }

	 $aLines = file($aSql);
	 $aBuffer = '';
	 $aStatements = 0;

	 foreach($aLines as $aCmd) {
		 $aBuffer .= $aCmd;

		 if(strpos(trim($aCmd), ');') !== false) {
			 $aDb->exec($aBuffer);
			 $aBuffer = '';
			 $aStatements++;
		 }
	 }

	 echo "Success! Performed statements: " . $aStatements . "\n";
	 exit(0);

} else if($aDump) {
    $aStmt = $aDb->prepare("SELECT * FROM titles WHERE 1");
    $aStmt->execute();

    $aRows = array();

    while($aRow = $aStmt->fetch(PDO::FETCH_OBJ)) {
        $aRows[$aRow->id] = $aRow;
    }

    $aJson = json_encode($aRows, JSON_NUMERIC_CHECK | JSON_PRETTY_PRINT);

    echo "// Automatically generated by Scifibot command line manager.\n";
    echo "// Date: ".date('Y-m-d H:i:s')."\n\n";
    echo "var ScifiBot = ScifiBot || {};\n\n";
    echo "ScifiBot.config.DATABASE_DATA =\n";
    echo $aJson . ";\n\n";

    exit(0);
}

?>
